stages:
  - build
  - test

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

build:
  image: docker:latest
  stage: build
  tags:
    - docker
    - build
  services:
    - name: docker:20-dind
      command: [ "--registry-mirror", "https://mirror.gcr.io" ]
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build --network host -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - main

unit_test:
  image: golang:1.24
  stage: test
  tags:
    - staff
  script:
    - apt-get install make
    - make test

lint:
  image: golangci/golangci-lint:v1.64.8
  stage: test
  tags:
    - staff
  script:
    - make lint

#deploy:
#  image: docker:20-git
#  stage: deploy
#  tags:
#    - docker
#    - staff
#  script:
#    - chmod og= $ID_RSA
#    - apk update && apk add openssh-client
#    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
##    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker container rm -f nemedia-duckdb-server || true"
##    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker run -d  --restart unless-stopped --name nemedia-duckdb-server --env APP_SERVICE=api -p 8092:8080 --mount type=bind,source=$BASE_PATH/logs,target=/app/logs --mount type=bind,source=$BASE_PATH/.env,target=/app/.env --mount type=bind,source=$BASE_PATH/data,target=/app/data $TAG_COMMIT"
#    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker logout $CI_REGISTRY"
#  environment:
#    name: production
#  only:
#    - main
#clean:
#  image: docker:20-git
#  stage: clean
#  tags:
#    - docker
#    - staff
#  script:
#    - chmod og= $ID_RSA
#    - apk update && apk add openssh-client
#    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2525 $SERVER_USER@$SERVER_IP "docker images registery.viadstaff.com/inxo/duckdb-sql/main --filter="before=$TAG_COMMIT" -q | xargs docker rmi"
#  environment:
#    name: production
#  when: manual
#  only:
#    - main